from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    file = Path(path)
    text = file.read_text()
    if new in text:
        return
    if old not in text:
        raise SystemExit(f'Expected block not found in {path}')
    file.write_text(text.replace(old, new, 1))


replace_once(
    'server.ts',
    """  return { text: cleanRoleplayOutput(text), modelUsed, latencyMs: Date.now() - startTime };\n}""",
    """  const cleanedText = cleanRoleplayOutput(text);\n  if (!cleanedText) {\n    throw new Error(`OpenRouter lieferte für Modell ${modelUsed} keinen nutzbaren finalen Antworttext.`);\n  }\n  return { text: cleanedText, modelUsed, latencyMs: Date.now() - startTime };\n}""",
)

replace_once(
    'server.ts',
    """  return generateOpenRouterResponse({\n    systemPrompt,\n    messages: [{ role: 'user', content: prompt }],\n    ...generation,\n    defaultModel: IMITATE_DEFAULT_MODEL,\n    modelOverride: settings?.modelName,\n    timeoutMs: 180000,\n  });\n}""",
    """  const request = {\n    systemPrompt,\n    messages: [{ role: 'user' as const, content: prompt }],\n    ...generation,\n  };\n\n  try {\n    return await generateOpenRouterResponse({\n      ...request,\n      defaultModel: IMITATE_DEFAULT_MODEL,\n      modelOverride: settings?.modelName,\n      timeoutMs: 120000,\n    });\n  } catch (primaryError: any) {\n    // Respect an explicit user model override. Automatic fallback only applies to\n    // the built-in free Imitate model.\n    if (String(settings?.modelName || '').trim()) throw primaryError;\n\n    console.warn(\n      `Imitate model ${IMITATE_DEFAULT_MODEL} failed (${primaryError?.message || primaryError}). ` +\n      `Retrying with free chat model ${CHAT_DEFAULT_MODEL}...`\n    );\n\n    try {\n      return await generateOpenRouterResponse({\n        ...request,\n        defaultModel: CHAT_DEFAULT_MODEL,\n        timeoutMs: 120000,\n      });\n    } catch (fallbackError: any) {\n      throw new Error(\n        `Imitate Me konnte weder mit ${IMITATE_DEFAULT_MODEL} noch mit ${CHAT_DEFAULT_MODEL} einen Entwurf erzeugen. ` +\n        `Letzter Fehler: ${fallbackError?.message || fallbackError}`\n      );\n    }\n  }\n}""",
)

old_poller = """  useEffect(() => {\n    if (!activeImitateJobId) return;\n    let isSubscribed = true;\n    const interval = setInterval(async () => {\n      try {\n        const res = await fetch(`/api/jobs/${activeImitateJobId}`);\n        if (!res.ok) return;\n        const job = await res.json();\n        if (job.status === 'completed' && isSubscribed) {\n          clearInterval(interval);\n          removePendingJob(activeImitateJobId);\n          setActiveImitateJobId(null);\n          setIsImitating(false);\n          if (job.result?.draft) {\n            setInput((prev) => (prev.trim() ? `${prev}\\n\\n${job.result.draft}` : job.result.draft));\n            addLog({\n              type: 'imitate',\n              status: 'success',\n              model: job.result.modelUsed || settings.modelName || 'openrouter',\n              latencyMs: job.result.latencyMs,\n              message: 'Imitate Me Entwurf in Eingabefeld eingefügt',\n            });\n          }\n        } else if ((job.status === 'failed' || job.status === 'error') && isSubscribed) {\n          clearInterval(interval);\n          removePendingJob(activeImitateJobId);\n          setActiveImitateJobId(null);\n          setIsImitating(false);\n          setErrorMessage(job.error || 'Konnte keinen Entwurf generieren.');\n          addLog({\n            type: 'error',\n            status: 'error',\n            model: settings.modelName || 'openrouter',\n            message: job.error || 'Imitate Job fehlgeschlagen',\n          });\n        }\n      } catch (err) {\n        console.warn('Imitate poll error', err);\n      }\n    }, 1200);\n    return () => {\n      isSubscribed = false;\n      clearInterval(interval);\n    };\n  }, [activeImitateJobId, settings.modelName]);\n"""

new_poller = """  useEffect(() => {\n    if (!activeImitateJobId) return;\n    let isSubscribed = true;\n    const interval = setInterval(async () => {\n      try {\n        const res = await fetch(`/api/jobs/${activeImitateJobId}`);\n        if (!res.ok) {\n          if (isSubscribed && res.status === 404) {\n            clearInterval(interval);\n            removePendingJob(activeImitateJobId);\n            setActiveImitateJobId(null);\n            setIsImitating(false);\n            const message = 'Der Imitate-Me-Job ist auf dem Server nicht mehr vorhanden. Bitte erneut versuchen.';\n            setErrorMessage(message);\n            addLog({\n              type: 'error',\n              status: 'error',\n              model: settings.modelName || 'openrouter',\n              message,\n            });\n          }\n          return;\n        }\n        const job = await res.json();\n        if (job.status === 'completed' && isSubscribed) {\n          clearInterval(interval);\n          removePendingJob(activeImitateJobId);\n          setActiveImitateJobId(null);\n          setIsImitating(false);\n          const draft = String(job.result?.draft || '').trim();\n          if (draft) {\n            setInput((prev) => (prev.trim() ? `${prev}\\n\\n${draft}` : draft));\n            addLog({\n              type: 'imitate',\n              status: 'success',\n              model: job.result.modelUsed || settings.modelName || 'openrouter',\n              latencyMs: job.result.latencyMs,\n              message: 'Imitate Me Entwurf in Eingabefeld eingefügt',\n            });\n          } else {\n            const message = 'Imitate Me wurde beendet, aber das Modell hat keinen nutzbaren Entwurf geliefert.';\n            setErrorMessage(message);\n            addLog({\n              type: 'error',\n              status: 'error',\n              model: job.result?.modelUsed || settings.modelName || 'openrouter',\n              latencyMs: job.result?.latencyMs,\n              message,\n            });\n          }\n        } else if ((job.status === 'failed' || job.status === 'error') && isSubscribed) {\n          clearInterval(interval);\n          removePendingJob(activeImitateJobId);\n          setActiveImitateJobId(null);\n          setIsImitating(false);\n          setErrorMessage(job.error || 'Konnte keinen Entwurf generieren.');\n          addLog({\n            type: 'error',\n            status: 'error',\n            model: settings.modelName || 'openrouter',\n            message: job.error || 'Imitate Job fehlgeschlagen',\n          });\n        }\n      } catch (err) {\n        console.warn('Imitate poll error', err);\n      }\n    }, 1200);\n    return () => {\n      isSubscribed = false;\n      clearInterval(interval);\n    };\n  }, [activeImitateJobId, settings.modelName]);\n"""

replace_once('src/App.tsx', old_poller, new_poller)

print('Imitate runtime reliability patch applied')
