export type Role = 'character' | 'lidii' | 'dean';

export interface ChatImage {
  url: string;
  caption?: string;
  prompt?: string;
  isUserUploaded?: boolean;
}

export interface Message {
  id: string;
  role: 'character' | 'lidii' | 'dean';
  speakerName?: string;
  content: string;
  timestamp: number;
  image?: ChatImage;
  metadata?: {
    isImitated?: boolean;
    editedAt?: number;
    tokensUsed?: number;
    modelUsed?: string;
  };
}

export interface MemoryItem {
  id: string;
  category: 'plot' | 'detail' | 'trait' | 'relationship';
  content: string;
  keys?: string[];
  createdAt: number;
}

export interface StoryContext {
  canonBackground?: string;
  currentScene: string;
  sceneSummary: string;
  keyEvents: string[];
  memories?: MemoryItem[];
}

export type CharacterProfile = Character;

export type ImageFrequency = 'disabled' | 'rare' | 'occasional' | 'frequent' | 'very_frequent';

export type DominanceLevel =
  | 'level_1_very_restrained'
  | 'level_2_gentle'
  | 'level_3_lightly_leading'
  | 'level_4_confident'
  | 'level_5_dominant'
  | 'level_6_strongly_dominant'
  | 'level_7_controlling'
  | 'level_8_very_controlling'
  | 'level_9_extremely_dominant'
  // Backward compatibility:
  | 'dominant'
  | 'balanced'
  | 'submissive'
  | 'restrained';

export type PacingMode = 'slow_burn' | 'balanced' | 'fast';
export type PlotInitiativeLevel = 'high' | 'medium' | 'low';

export interface Character {
  id: string;
  name: string;
  avatarUrl: string;
  age?: string;
  appearance: string;
  description?: string; // Character Card V2: description
  personality: string;
  background: string;
  relationshipToPlayer: string;
  writingStyle: string;
  toneOfVoice: string;
  typicalPhrases: string;
  playerAddressName: string; // e.g. "Lidii"
  addressMode?: 'auto' | 'custom'; // 'auto': dynamically generated by AI based on context
  nicknames?: string; // Optional custom guidance or specific terms
  thoughtsEnabled: boolean; // Render thoughts in italics
  initiativeLevel: 'high' | 'medium' | 'low';
  plotInitiative?: PlotInitiativeLevel;
  pacing?: PacingMode;
  flirtBehavior: 'intense' | 'playful' | 'subtle' | 'none';
  dominanceLevel: DominanceLevel;
  dynamics?: string[]; // Multi-select BDSM/RP dynamics & archetypes
  humorLevel?: 'dark' | 'dry' | 'playful' | 'serious';
  humorStyles?: string[]; // Multi-select humor traits
  behaviorRules: string;
  startPlot?: string; // Scenario / setting description for new chats
  scenario?: string; // Character Card V2: scenario
  startBehavior?: string; // How the character behaves at the start
  startPrompt?: string; // Character Card V2: first_mes
  firstMes?: string; // Character Card V2: first_mes alias
  exampleDialogues?: string; // Character Card V2: mes_example (<START> blocks)
  mesExample?: string; // Character Card V2: mes_example alias
  systemPrompt?: string; // Character Card V2: system_prompt
  postHistoryInstructions?: string; // Character Card V2: post_history_instructions
  alternateGreetings?: string[]; // Character Card V2: alternate_greetings
  characterBook?: any; // Character Card V2: character_book
  creatorNotes?: string; // Character Card V2: creator_notes
  tags?: string[]; // Character Card V2: tags
  creator?: string; // Character Card V2: creator
  characterVersion?: string; // Character Card V2: character_version
  extensions?: Record<string, any>; // Character Card V2: extensions
  imageFrequency?: ImageFrequency;
  imageStyleDescription?: string;
  customInstructions?: string;
  memories: MemoryItem[];
  createdAt: number;
  updatedAt: number;
}

export type ChatLanguage = 'de' | 'en';

export interface ChatCharacterSettings {
  dominanceLevel?: DominanceLevel;
  dynamics?: string[];
  humorLevel?: 'dark' | 'dry' | 'playful' | 'serious';
  humorStyles?: string[];
  initiativeLevel?: 'high' | 'medium' | 'low';
  plotInitiative?: PlotInitiativeLevel;
  pacing?: PacingMode;
  flirtBehavior?: 'intense' | 'playful' | 'subtle' | 'none';
  thoughtsEnabled?: boolean;
  writingStyle?: string;
  toneOfVoice?: string;
  typicalPhrases?: string;
  behaviorRules?: string;
  exampleDialogues?: string;
  postHistoryInstructions?: string;
  customInstructions?: string;
}

export interface ChatSession {
  id: string;
  characterId: string;
  title: string;
  language: ChatLanguage;
  characterSettings?: ChatCharacterSettings;
  messages: Message[];
  storyContext: StoryContext;
  createdAt: number;
  updatedAt: number;
  isArchived?: boolean;
  lastJobId?: string;
}

export interface ModelSettings {
  provider: 'openrouter';
  modelName: string;
  temperature: number;
  maxOutputTokens: number;
  contextWindowSize: number;
}

export interface AsyncJob {
  id: string;
  type: 'chat' | 'imitate' | 'summarize' | 'photo' | 'start-chat';
  characterId?: string;
  chatId?: string;
  status: 'running' | 'completed' | 'failed';
  result?: {
    content?: string;
    draft?: string;
    image?: ChatImage;
    modelUsed?: string;
    latencyMs?: number;
    role?: string;
    speakerName?: string;
  };
  error?: string;
  createdAt: number;
  completedAt?: number;
}

export interface ApiLog {
  id: string;
  timestamp: number;
  type: 'chat' | 'imitate' | 'summarize' | 'photo' | 'start-chat' | 'error' | 'info';
  status: 'pending' | 'success' | 'error';
  model: string;
  latencyMs?: number;
  message?: string;
  details?: any;
}
